### PR TITLE
IGAPP-397: Enable sentry for web

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by klinzo — APPROVED** [review]
Did you check whether errors are actually showing up in sentry?

**Comment by SteffiStuffel** [comment]
> Did you check whether errors are actually showing up in sentry?

No, i didn't. Thought this is only possible in production. Can you give me a short explanation how to test it?

**Comment by maxammann** [comment]
1. Add a "throw new Error()" somewhere in a render funciton
1. Create a release build
2. Launch a webserver in the directory with the index.html: `python3 -m http.server`
3. Open the page and seee it crashing.
4. Check sentry.tuerantuer.org

**Review by maxammann — APPROVED** [review]

**Comment by klinzo** [comment]
>     1. Add a "throw new Error()" somewhere in a render funciton
> 
>     2. Create a release build
> 
>     3. Launch a webserver in the directory with the index.html: `python3 -m http.server`
> 
>     4. Open the page and seee it crashing.
> 
>     5. Check sentry.tuerantuer.org

Should we add this somewhere in the Readme (How to run a release build)?

**Comment by SteffiStuffel** [comment]
> Did you check whether errors are actually showing up in sentry?

Now i checked it and its working.

**Review by klinzo — APPROVED** [review]
If you want you can add how to run a release build to the documentation :)

**Pull request merged**
