### PR TITLE
IGAPP-186: Changed every occurence of Image to FastImage.

### PR DESCRIPTION
**Pull request by SimonVortkamp**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it here: https://issues.tuerantuer.org/browse/IGAPP-186

### CODE REVIEW

**Review by klinzo — CHANGES_REQUESTED** [review]
This somehow broke the images, e.g.
* IntroSlide app icon, is not using the right icon anymore, same for integreat icon on dashboard (or: the wrong format)
* Second intro slide icon is a little bit cut in left bottom corner
* No location marker is shown anymore on the landing page, same for navigation tiles on dashboard and feedback icons

**Comment by klinzo** [comment]
There is already a custom Image component, maybe you can use it. But not sure about that.

**Comment by maxammann** [comment]
Seems like RN fast image does not support this: https://github.com/DylanVann/react-native-fast-image/issues/248
I think we should revert this to Image for everything which uses images from an `import`. 

We could also refactor our Image component and then use this one everywhere:
`./native/src/modules/common/components/Image.js`

There is a check: typeof uri === 'number'
If that is true then we simply could use the Image component from React-Native. If that is false then continue and use FastImage.


We could also just remove FastImage everywhere and just use Image to simplify our code.

**Review by maxammann — CHANGES_REQUESTED** [review]
I'm sorry simon, but I think we have to adjust here as the solution in the issue does not work :D

**Pull request closed without merging**
