### PR TITLE
IGAPP-715: Code-Split routes

### PR DESCRIPTION
**Pull request by Schedulaar**
See #377 for more information.

### CODE REVIEW

**Comment by f1sh1918** [comment]
Great Work! I tested it and for me its fine.
As far as i could check it, we saved about ~300kb in some cases

**Review by f1sh1918 — APPROVED** [review]

**Review by Taggotty — APPROVED** [review]
You''ll need to add types to the Routes in `CityContentSwitcher` either type the props inline like `ComponentProps<typeof EventsPage>` or think of a fitting generic function :)

**Review by klinzo — APPROVED** [review]
Nice :tada:

**Comment by Schedulaar** [comment]
So typescript was not nice to me... This took a few hours to find the right tweaks to make it work without tsignores... :/ I hope it still works now 🙈

**Comment by klinzo** [comment]
> So typescript was not nice to me... This took a few hours to find the right tweaks to make it work without tsignores... :/ I hope it still works now see_no_evil
> 
> ... But hey, now I have removed more lines than I added in this PR :D

Do you think it would have been easier with flow? :D

**Comment by klinzo** [comment]
Can confirm it still works :+1: Also, looks better in some places then before, so well done :tada:

**Comment by Schedulaar** [comment]
> > So typescript was not nice to me... This took a few hours to find the right tweaks to make it work without tsignores... :/ I hope it still works now see_no_evil
> > ... But hey, now I have removed more lines than I added in this PR :D
> 
> Do you think it would have been easier with flow? :D

I think our routes / value passing was not even typed in flow :D so probably yes^^

**Comment by klinzo** [comment]
@maxammann do you want to have a look as well?

**Review by Taggotty — APPROVED** [review]

**Review by maxammann — APPROVED** [review]
Looks good!

**Comment by klinzo** [comment]
No I think we can merge it, will do so before you have to merge in main again :D

**Pull request merged**
