### PR TITLE
IGAPP-551 Add language Serbian (for Malte)

### PR DESCRIPTION
**Pull request by Znippet**
Tested:
image
image

### CODE REVIEW

**Review by klinzo — APPROVED** [review]
I don't get your screenshot tbh. AFAIK we don't have any Cyrillic UI app translations for Serbian and no Latin Serbian translations in the CMS, but your screenshot shows it the other way round :thinking: 

_I added Cyrillic UI app translations but I didn't commit them.
I renamed the old "sr" to latin-sr.
Then I added some manual translations for "sr-Cyrl" so the old "sr" could fall back to it. 
So what you see are my (uncommited) test-translations for cyrillic_

**Review by klinzo — CHANGES_REQUESTED** [review]
We have to adjust the translations in the malte.json and aschaffenburg.json overwrite files as well, forgot that myself as well probably. We may also have to adjust it for the whole bunch of Persian and Kurdish languages as well, must not be done in your PR though.
Tested on android and web, apart from the thing mentioned above everything works as expected.

_Updated malte.json. aschaffenburg.json doesn't have serbian at all until now so no changes here_

**Review by maxammann — APPROVED** [review]
looks good

**Comment by maxammann** [comment]
@klinzo fixing malte.json and aschaffenburg.json should be done soon I think. At least before merging in new translations. Else this gets quite complicated later and nobody remembers.

**Comment by klinzo** [comment]
@maxammann did not find any things that need fixing, so I guess we are fine.

**Review by klinzo — APPROVED** [review]

**Pull request merged**
