### PR TITLE
IGAPP-403: Move builders to api-client

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by klinzo** [comment]
Use of the builders can be increased in future PRs if there are changes anyway. I think this could be a gradual change as well. Otherwise this PR would have been gotten much bigger than it is already.

**Comment by klinzo** [comment]
Some native tests in the DataConnector are failing because of moment. Any idea why this happens? I don't have a clue... the iso strings are the same and moment versions as well :disappointed:

**Review by maxammann — APPROVED** [review]
nice removals :)

**Comment by klinzo** [comment]
@maxammann I think I found a relatively nice solutions for the overrides :)

**Review by Taggotty — APPROVED** [review]
Nice and tidy. 👍🏼

**Review by Taggotty — APPROVED** [review]

**Pull request merged**
