### PR TITLE
IGAPP-506: Add new languages to the Integreat app

### PR DESCRIPTION
**Pull request by maxammann**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by maxammann** [comment]
This PR is left open to have a reference where to merge in the new translations.

**Comment by klinzo** [comment]
These changes are only automatic prettier reformating, right?

**Comment by maxammann** [comment]
Not sure, we can drop them ofc, but this PR needs to stay open and languages need to be added to this PR. Else we could miss changes which happened between 31. March and today.

Do we have updates on this? This will also conflict with the refactoring probably.

**Comment by klinzo** [comment]
Sadly no updates yet, no.

**Comment by maxammann** [comment]
I merged this branch into IGAPP-506-malte-translations-new

**Pull request closed without merging**
