### PR TITLE
IGAPP-815: Store tarball instead of single files

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by Taggotty** [comment]
Do you have some more input for this?

**Review by SteffiStuffel — COMMENTED** [review]
Is this just for the IGAPP-815 Task and will be reverted or do we always want to do this?

**Comment by klinzo** [comment]
> Do you have some more input for this?

@Taggotty it is very tedious to download all files separately, by saving it as .tar.gz you just need to download one file and can just unpack it afterwards.

**Review by Taggotty — APPROVED** [review]

**Comment by klinzo** [comment]
> Is this just for the IGAPP-815 Task and will be reverted or do we always want to do this?

@SteffiStuffel I would just keep this as I don't see a reason not to keep it. Makes sense imo

**Pull request merged**
