### PR TITLE
IGAPP-697: Flipper not working with xcode v12.5

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by f1sh1918 — APPROVED** [review]

**Review by Taggotty — APPROVED** [review]

**Review by maxammann — CHANGES_REQUESTED** [review]
I stopped auto-merge because I want to leave a comment here :)

We should document that we did this in some Jira task. All these changes are not supported by React-Native. Flipper should get updated with React-Native. That means our react-native project is now in an unsupported state.

While it maybe oke, there are also some weird changes in the project.pbxproj file, which should not happen. If these are reverted and we add a note to the next upgrade task then I'm fine with merging.

**Comment by klinzo** [comment]
> I stopped auto-merge because I want to leave a comment here :)
> 
> We should document that we did this in some Jira task. All these changes are not supported by React-Native. Flipper should get updated with React-Native. That means our react-native project is now in an unsupported state.
> 
> While it maybe oke, there are also some weird changes in the project.pbxproj file, which should not happen. If these are reverted and we add a note to the next upgrade task then I'm fine with merging.

@maxammann where do you have the info from that flpper should only be updated together with react-native? The flipper getting started page states that react-native might ship with an outdated version and how to upgrade to the latest version: https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk

**Comment by maxammann** [comment]
> > I stopped auto-merge because I want to leave a comment here :)
> > We should document that we did this in some Jira task. All these changes are not supported by React-Native. Flipper should get updated with React-Native. That means our react-native project is now in an unsupported state.
> > While it maybe oke, there are also some weird changes in the project.pbxproj file, which should not happen. If these are reverted and we add a note to the next upgrade task then I'm fine with merging.
> 
> @maxammann where do you have the info from that flpper should only be updated together with react-native? The flipper getting started page states that react-native might ship with an outdated version and how to upgrade to the latest version: https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk

Oh oke it seems like my knowledge is outdated then. In that case only the changes in the project file should be reverted if there is no reason for them.

**Review by maxammann — APPROVED** [review]

**Comment by klinzo** [comment]
@maxammann tbh I am a little bit lost here. Without the `embed pods framework` build phase the build fails with the message that OpenSSL framework is not enabled, so seems like it is kind of needed. The `$(inherited)` prevent the following warning:
[!] The `Integreat [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Integreat/Pods-Integreat.release.xcconfig'. This can lead to problems with the CocoaPods installation
I think we already had that some time ago and switched to inherited. Do you have any more information on whether this is fine or not?

**Review by maxammann — APPROVED** [review]
Oke then this is probably because of an upgrade of Pod or the updated dependencies changed this.

**Pull request merged**
