### PR TITLE
IGAPP-429: Add Last Update

### PR DESCRIPTION
**Pull request by Taggotty**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by maxammann — APPROVED** [review]
I will create a task today in the afternoon which will fix date formatting for de-si. This could break this this. So be aware to merge early (or later) :D

**Review by klinzo — COMMENTED** [review]
Are you sure this works? I don't see any last update :see_no_evil: 
image

Also a release note would be nice :)

**Comment by Taggotty** [comment]
> Are you sure this works? I don't see any last update  I think I am on the right branch...

Hmm. At least for me it worked. I will take another look on it. Thx for checking.

> Also a release note would be nice :)

👍🏼

**Comment by Taggotty** [comment]
Will be closed for now as this should have been the implementation for native and not web.

**Pull request closed without merging**
