### PR TITLE
IGAPP-583: Update translations and remove old and unused translations

### PR DESCRIPTION
**Pull request by f1sh1918**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by klinzo — COMMENTED** [review]
Not sure if we should merge this already. Things to consider:
* We did not really decide on what text to use here or gave it any deeper thoughts
* The new message currently does not really make sense for users as the location feature is still in development

**Comment by Taggotty** [comment]
> Not sure if we should merge this already. Things to consider:
> 
> * We did not really decide on what text to use here or gave it any deeper thoughts
> * The new message currently does not really make sense for users as the location feature is still in development

So you'd postpone this issue until after we release POIs?

**Comment by klinzo** [comment]
> So you'd postpone this issue until after we release POIs?

Not until after but until we release them. So probably together with enabling the feature flag.

**Review by maxammann — APPROVED** [review]

**Review by klinzo — CHANGES_REQUESTED** [review]
See above, it does not make sense to merge this right now as long as we did not decide on the right texts/translations.

**Review by klinzo — APPROVED** [review]

**Pull request merged**
