### PR TITLE
APICLIENT-41: http://integreat/ is not a valid URL

### PR DESCRIPTION
**Pull request by maxammann**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by klinzo** [comment]
I'd close this, will be upgraded in #60 and #61 anyway :)

**Comment by maxammann** [comment]
The config is still valuable :)

**Comment by maxammann** [comment]
The config is still valuable :)

**Review by klinzo — APPROVED** [review]

**Comment by maxammann** [comment]
I cherry picked that commit. This will be resolved when the api-client is merged to the repostiory

**Pull request closed without merging**
