### PR TITLE
IGAPP-546: Remove require cicle in category model

### PR DESCRIPTION
**Pull request by zankerbe**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by klinzo — APPROVED** [review]
:+1:

**Review by SteffiStuffel — CHANGES_REQUESTED** [review]
I think it would make sense to use the isLeaf method also in Categories.js (line 137) (native). Or is there a reason, why you didn't use it there?

**Comment by klinzo** [comment]
> I think it would make sense to use the isLeaf method also in Categories.js (line 137) (native). Or is there a reason, why you didn't use it there?

Probably makes sense to use it there, yes. This Issue wasn't about using the `isLeaf` function wherever possible but instead just to refactor previous usages, so I'd say it is @zankerbe 's decision if he wants to use it there as well.

**Review by maxammann — APPROVED** [review]

**Review by Taggotty — APPROVED** [review]

**Comment by zankerbe** [comment]
> 
> 
> I think it would make sense to use the isLeaf method also in Categories.js (line 137) (native). Or is there a reason, why you didn't use it there?

Since Categories.js doesn't use an instance of CategoriesMapModel the isLeaf function cannot be directly used here. I'd prefer to leave it as it is.

**Review by SteffiStuffel — APPROVED** [review]

**Pull request merged**
