### PR TITLE
IGAPP-689: Move app translations

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by klinzo** [comment]
Removed following keys:
* `localNewsAlternative`
* `pageTitles.pois`
Fixed the following keys:
* `pageTitles.tuNews` (`tünews` to `tünews INTERNATIONAL`)

**Review by SteffiStuffel — APPROVED** [review]
Tested in Chrome, everything is translated :)

**Review by Taggotty — APPROVED** [review]

**Comment by Taggotty** [comment]
Tested on firefox.

**Comment by klinzo** [comment]
@maxammann what do you think about this? Should not lead to any problems with translations, right?

**Pull request merged**
