### PR TITLE
IGAPP-194: Stabilize e2e tests

### PR DESCRIPTION
**Pull request by Taggotty**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

Most of the time the ios e2e tests timed out. After looking at the appium logs of the failed tests you could see the error message `Capability 'waitForQuiescence' changed from string to boolean. This may cause unexpected behavior`. After some search I also found that this capability can lead to very slow or even stuck tests (more details [here](https://github.com/appium/appium-xcuitest-driver#desired-capabilities)). I don't think there is a good way to test whether the tests will work more stable after this change though. :)

### CODE REVIEW

**Review by klinzo — APPROVED** [review]

**Review by maxammann — APPROVED** [review]
That is quite weird as we did not pass `waitForQuiescence` before. Is there maybe a default which uses string? If yes then we should maybe update the webdriver dependency

**Comment by Taggotty** [comment]
Hmm. Somehow the parameter is still not set correctly. I will take another look at that.

**Comment by Taggotty** [comment]
> That is quite weird as we did not pass `waitForQuiescence` before. Is there maybe a default which uses string? If yes then we should maybe update the webdriver dependency

Normally this parameter should be set by browserstack, I think. Webdriver shouldn't have anything to do with that...But I think you can also pass Automate Capabilities to browserstack. As stated above, I will take another look at that.

**Comment by Taggotty** [comment]
> Hmm. Somehow the parameter is still not set correctly. I will take another look at that.

Fixed. You have to pass it as a string so it is converted to a boolean later, otherwise the boolean will be interpreted as an object an therefore as a astring 🤦🏼

**Comment by maxammann** [comment]
@Taggotty but probably then this PR will do nothing right? I mean we are passing it now as string to browserstack. Or did you test it again?

**Comment by Taggotty** [comment]
> @Taggotty but probably then this PR will do nothing right? I mean we are passing it now as string to browserstack. Or did you test it again?

I tested it and now it works fine. A string will be parsed to bool, but a bool wirl be parsed to string. That was what I tried to explain.

**Pull request merged**
