### PR TITLE
IGAPP-849: Upgrade firebase

### PR DESCRIPTION
**Pull request by f1sh1918**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

Tested on ios native and android emulator.

**To Test:**
Could not get notification on android native, maybe related to my custom rom.
Can someone test this please with an android native device
Since i had to update cocoapods & gems for new firebase version please also test on ios

Send push notification
https://cms-test.integreat-app.de/testumgebung/wp-admin/admin.php?page=fb-pn

### CODE REVIEW

**Review by klinzo — APPROVED** [review]
Tested on android emuator

**Comment by klinzo** [comment]
Yep, probably related to this PR. You did oc not test this anyway though since you had another firebase version installed. But I guess this is fine. @maxammann perhaps you could test this once on a iPhone?

**Comment by maxammann** [comment]
@klinzo 20h is not enough time to react :sweat_smile:

**Comment by klinzo** [comment]
@maxammann this can still be tested :D

**Pull request merged**
