### PR TITLE
IGAPP-451: Redirect landing route to fixed city

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by maxammann — APPROVED** [review]
Isn't this already working when going to https://webnext.aschaffenburg.app/ ?

**Comment by klinzo** [comment]
> Isn't this already working when going to https://webnext.aschaffenburg.app/ ?

Only partly. It's working for `/`, `/landing` and `/aschaffenburg`, but not for `/landing/de`. E.g. https://webnext.aschaffenburg.app/landing/de/ is not redirecting.

**Comment by maxammann** [comment]
I actually would be fine as how it already is. I mean there should be no way of knowing that link. And if you manually try it then this is acceptable behavior imo.

As long as we do not have a href to that location we do not require that complexity.

**Comment by SteffiStuffel** [comment]
Tested this, works as expected

**Comment by klinzo** [comment]
I'd merge it, not too much complexity imo and I think unexpected behavior is never good. Other opinions?

**Review by SteffiStuffel — APPROVED** [review]

**Comment by klinzo** [comment]
Won't do as this is not a url someone lands accidentally and it adds complexity.

**Pull request closed without merging**
